// <auto-generated />
using System;
using CSGOStats.Services.HistoryParse.Aggregate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CSGOStats.Services.HistoryParse.Data.EF.Migrations
{
    [DbContext(typeof(MigrationsDataContext))]
    [Migration("20200201094011_AddedCreateDatetimeForParsedMatch")]
    partial class AddedCreateDatetimeForParsedMatch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CSGOStats.Services.HistoryParse.Aggregate.Entities.ParsedMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("2020-02-01T09:40:11.2382662Z (ISO)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ParsedMatch","HistoryParse");
                });
#pragma warning restore 612, 618
        }
    }
}
